baseurl: ""
url: "http://mandygrg.github.io"

# Site settings
title: Beautician Mandy (BM)
email: mandykanchi@gmail.com
description: "Beauty Saloon at your Home"


# Team names, titles and social links
people:
- name: Mandy
  pic: 1
  position: Independent Beautician
  social:
    - title: facebook
      url: https://www.facebook.com/mandira.ghimire.967
    - title: instagram
      url: https://instagram.com/offlinequeenii/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/mandira.ghimire.967
  - title: instagram
    url: https://instagram.com/offlinequeenii/

# Postal address (add as many lines as necessary)
address:
  - line: Sr No 147, Ghawate Nagar
  - line: Mundha-Manjari Road, Manjari
  - line: Pune, Maharashtra, India (Pin No 412307)

# Build settings
markdown: kramdown
permalink: pretty
